kind = "web"
previewPath = "/"
title = "Like By Nirob"
version = "1.0.0"
id = "artifacts/slv"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20016

[services.development]
run = "pnpm --filter @workspace/slv run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/slv", "run", "build" ]
publicDir = "artifacts/slv/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20016"
BASE_PATH = "/"
